"""add_structured_goal_fields

Revision ID: f1a2b3c4d5e6
Revises: e6c9f3dbae2d
Create Date: 2024-11-26 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, None] = 'e6c9f3dbae2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('due_date', sa.String(), nullable=True))
    op.add_column('goals', sa.Column('success_metrics', sa.Text(), nullable=True))
    op.add_column('goals', sa.Column('manager_support', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'manager_support')
    op.drop_column('goals', 'success_metrics')
    op.drop_column('goals', 'due_date')
    # ### end Alembic commands ###
